[package]
name = "litechannel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spake2 = "0.2.0"
rand = "0.8.0"

[dev-dependencies]
qrcode = "0.11"